### ISSUE TITLE
Give credits to JSM

### ISSUE THREAD

**Issue by Zaid-maker** [japrweb/music-app-clone#1]
This project made by a YouTube Javascript Mastery, please give him a credit for him work.

**Comment by japrweb** [comment]
Hi DevMirza, thank you for your comment. 

I've updated the README to give credit to the JavaScript Mastery team for their original work. Additionally, I apologize if my oversight gave the impression that I was not giving them proper recognition. However, please keep in mind that using my version of the project excessively can negatively impact other users who also want to utilize it. So, I kindly ask that you avoid doing so again in the future. Best regards!
